"""empty message

Revision ID: 98eaaf86a1a4
Revises: 8f1fc1607bfe
Create Date: 2023-11-24 16:36:54.363784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98eaaf86a1a4'
down_revision = '8f1fc1607bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Task', schema=None) as batch_op:
        batch_op.drop_index('ix_Task_quand')
        batch_op.drop_column('quand')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quand', sa.VARCHAR(length=255), nullable=False))
        batch_op.create_index('ix_Task_quand', ['quand'], unique=False)

    # ### end Alembic commands ###
